### ISSUE TITLE
Convert Stadia (linux) save to pc

### ISSUE THREAD

**Issue by fulkaffe** [linuslin0/ACST#100]
Would it be possible to do with this tool?! Tried but no go :-(

**Comment by fulkaffe** [comment]
[Assassin_s Creed Odyssey_1013_gamesave.zip](https://github.com/linuslin0/ACST/files/9998301/Assassin_s.Creed.Odyssey_1013_gamesave.zip)

**Comment by fulkaffe** [comment]
There is also a json file. This is what it contains

{
  "applicationName": "Assassin\u0027s Creed Odyssey",
  "values": {
    "FileName": "TWFudWFsU2F2ZTAy"
  },
  "timestamp": "2022-06-25T12:28:43.205979744Z",
  "saveId": 1013
}

**Comment by linuslin0** [comment]
#20 
Stadia saves are not compatible with the Windows version of this game.
