### ISSUE TITLE
Assassin's creed 3 (not remastered)

### ISSUE THREAD

**Issue by jimmy10815** [linuslin0/ACST#101]
Hello can you convert this save file into AC3? sorry my pc is weak... :) and does anyone have a 100% completed save?
[ac3r.zip](https://github.com/linuslin0/ACST/files/10089676/ac3r.zip)

**Comment by linuslin0** [comment]
remastered saves can't be loaded in the original version of this game.

**Comment by SuperJelle** [comment]
What about the other way around - can an original save game be converted to work on the remaster?

**Comment by linuslin0** [comment]
> What about the other way around - can an original save game be converted to work on the remaster?

It won't work. Only AC Liberation HD saves could be made to work with its remaster.
