### ISSUE TITLE
It's great, and I also want to modify: the archive of the Assassin's Creed Brotherhood, is the author interested in studying it?

### ISSUE THREAD

**Issue by 759852125** [linuslin0/ACST#102]
It's great, and I also want to modify: the archive of the Assassin's Creed Brotherhood, is the author interested in studying it?

Provide an archive file:
[ACBROTHERHOODSAVEGAME0.zip](https://github.com/linuslin0/ACST/files/10175405/ACBROTHERHOODSAVEGAME0.zip)

**Comment by 759852125** [comment]
> 我不熟悉修改实际保存数据。你想修改什么东西？

Assassin's Creed Brotherhood will recruit recruits to fight, but the maximum can only recruit 12 and play 12 at the same time, I want to break through this limit, in order to achieve unlimited number of recruits and the number of battles

**Comment by 759852125** [comment]
> I am not familiar with modifying the actual save data. What stuff do you want to modify?

I want to modify the number of Assassin recruits that have been recruited. The mandatory maximum in the game is 12

**Comment by linuslin0** [comment]
I would start with memory editing see if it's possible.

**Comment by 759852125** [comment]
> I would start with memory editing see if it's possible.

I am very interested in studying this game, and I hope to or discuss with you.
I searched for the "Cheat Engine" of this game on the Internet, and there are too few references.
I am from mainland China, and I am translating through Google, so there may be grammatical flaws in my reply..

**Comment by 759852125** [comment]
> I would start with memory editing see if it's possible.

https://youtu.be/XNttOxlwafQ

This video is the result of my research in the past few days, and I still have the following things to achieve
1. All the guards will immediately attack me without the alert bar (you don't need to alert when you see Ezio directly attacking)
2. The refresh rate of novice assassin recruits is increased or accelerated. The best effect is that after killing four guards and finishing the dialogue with assassin recruits, a new wave of novice assassin recruits in the current area will be refreshed immediately
3. Skip the dialogue of assassin recruits directly, or customize the plot playback speed of the dialogue with assassin recruits
4. Aim at the enemy at a longer distance (because summoning recruits requires a certain approach or distance to highlight the enemy)

**Comment by 759852125** [comment]
如果你也有兴趣研究
想请教一下联系方式，比如Telegram, WhatsApp等聊天平台

**Comment by linuslin0** [comment]
> > I would start with memory editing see if it's possible.
> 
> https://youtu.be/XNttOxlwafQ
> 
> This video is the result of my research in the past few days, and I still have the following things to achieve
> 
> 1. All the guards will immediately attack me without the alert bar (you don't need to alert when you see Ezio directly attacking)
> 2. The refresh rate of novice assassin recruits is increased or accelerated. The best effect is that after killing four guards and finishing the dialogue with assassin recruits, a new wave of novice assassin recruits in the current area will be refreshed immediately
> 3. Skip the dialogue of assassin recruits directly, or customize the plot playback speed of the dialogue with assassin recruits
> 4. Aim at the enemy at a longer distance (because summoning recruits requires a certain approach or distance to highlight the enemy)

Very impressive. Unfortunately I don't have lots of experience (and also time) to work on this at the moment. You might find better chances with ppl on https://fearlessrevolution.com/
