### ISSUE TITLE
My AC Valhalla save file was corrupted when i opened the game

### ISSUE THREAD

**Issue by PapiSmackMyAss** [linuslin0/ACST#104]
i've been play Valhalla crack version for awhile, and then i just bought the official game cause its on sale. i've been searchin for the entire night how to transfer my crack's save files into the game and ACST is the only way that my save's was read by the game (although is corrupted, lol) 

will you help me? im so close 
[save's file.zip](https://github.com/linuslin0/ACST/files/10180880/save.s.file.zip)

**Comment by linuslin0** [comment]
Please also upload a test save from the game on your account.

**Comment by PapiSmackMyAss** [comment]
> Please also upload a test save from the game on your account.

hey, thank you for your reply. after reading your "usage" instruction more carefully i finally got it works. 
thank you for your tools, man
