### ISSUE TITLE
mine gives an error after I do the conversion, in mine it says that the save files were corrupted, note I am on the latest version of assassins creed valhalla

### ISSUE THREAD

**Issue by xplayerbr** [linuslin0/ACST#108]
mine gives an error after I do the conversion, in mine it says that the save files were corrupted, note I am on the latest version of assassins creed valhalla

**Comment by linuslin0** [comment]
Please upload the saves you want to convert and a test save from the game on your account.

**Comment by XioNUndead** [comment]
So I have the same problem did everything right but I get the "Save Corrupted" too, so yeah
