### ISSUE TITLE
Failed to load save Assassins Creed Unity

### ISSUE THREAD

**Issue by ziv23451** [linuslin0/ACST#109]
so i download pirated Assassins Creed Unity from this site https://repack-games.com/assassins-creed-unity-gold-edition-free-download-v1/ and i love it and wanted to play online so i bought the game and tried to convert from my save3dmgames folder to uplay folder in C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\and the id but it saying faild to load save

**Comment by linuslin0** [comment]
Non-standard saves are not supported by this tool. There are steps to manually edit saves headers to let this tool load them. #96 
If you need a hand on that please upload saves you want to convert as well as a test save from the game on your account.
