### ISSUE TITLE
Unable to convert save files in 3DM save files.

### ISSUE THREAD

**Issue by sthrky22** [linuslin0/ACST#114]
I can't convert save files in 3DM version save files, I hope you can help. I would really love to get back my progress.
[Sequences 3-4-5-7-10-1-0-1-1657201260.zip](https://github.com/linuslin0/ACST/files/10418122/Sequences.3-4-5-7-10-1-0-1-1657201260.zip)

**Comment by linuslin0** [comment]
There are no 3DM saves in the archive you uploaded.
Please refer to #96 if you want to modify the non-standard saves to make them work with this tool.
