### ISSUE TITLE
Ac Valhalla save file of stadia version seems not to be compatible with this tool

### ISSUE THREAD

**Issue by giovi000** [linuslin0/ACST#116]
I am trying to convert Google Stadia save file of assassin's creed valhalla but it says Failed to load save. Is it possible to convert Stadia save file ? Can you help me? 
Saved file which i want to convert : [acv.zip](https://github.com/linuslin0/ACST/files/10500582/acv.zip)
Test file:
[testsave.zip](https://github.com/linuslin0/ACST/files/10500614/testsave.zip)

**Comment by linuslin0** [comment]
#105 
Stadia saves are not compatible with PC version of this game.
