### ISSUE TITLE
Please help I don't know how to use this tool

### ISSUE THREAD

**Issue by jimmy10815** [linuslin0/ACST#117]
How do I get both Decryption key and Encryption key? Thanks :)

**Comment by linuslin0** [comment]
Please refer to the README about the types of decryption/encryption ID.

**Comment by jimmy10815** [comment]
Can you convert this save into legal version ? I download it on nexusmods.
[All Outfits Save-362-1-0-1670311973.zip](https://github.com/linuslin0/ACST/files/10698390/All.Outfits.Save-362-1-0-1670311973.zip)

**Comment by linuslin0** [comment]
Please also provide a test save from the ACBF game on your account. If you want to do it yourself then you can load this save to the tool and put your ACBF activation key as the Encryption ID, or open a test save to let the tool handle that for you. As for Decryption ID, just check the Detect box.

**Comment by jimmy10815** [comment]
can you contact me with discord ? Drakus0507#2251

**Comment by linuslin0** [comment]
Sorry but I am only able to answer your question here if you still need help.

**Comment by Plopereuss** [comment]
Hello, any save file I want to open can't be opened. It just says failed to load savefile.
