### ISSUE TITLE
Watch Dogs Legion

### ISSUE THREAD

**Issue by FranciscoRibeiro03** [linuslin0/ACST#125]
Hey!
I was reading the other closed issues and you said that Watch Dogs Legion was not supported because it was using a different encryption method (or something along those lines).
I have some save files that I would like to convert from the EMPRESS version to Uplay version, but I have no clue on how to start doing this.
I have a bit of programming experience, but I have no clue on how to actually reverse engineer a file like this. Do you have some pointers on how to start?
Thanks!

**Comment by linuslin0** [comment]
Hey there, I don't think we can get anything useful by just looking at the save data. We will have to debug the game, which might be time consuming and challenging as I would expect stronger encryption was implemented for this game.

**Comment by FranciscoRibeiro03** [comment]
Thank you for your answer! I just didn't want to lose my game progress, as I was already at the middle of the game, but I ended up just finishing the game on the pirated version and started a new game (higher difficulty) on the Uplay version, to actually 100% the game (on the pirated version I just gave up, since I had bought the original version, and just did a speedrun of the main storyline, no side quests xD)
