### ISSUE TITLE
VirusTotal website detecta 5 threats out of 71.

### ISSUE THREAD

**Issue by BrotherTwoN** [linuslin0/ACST#126]
Bkav pro detects W32.AldetectMalware.64
Cybereason detects Malicious.f7df79
Trapmine detects Suspicious.low.ml.acorde
CrowdStrike detect Win/malicious_confidence_60% (D)
SecureAge detect malicious

Is it a false positive??

**Comment by linuslin0** [comment]
Yeah it's false positive might caused by the 7z self extracting exe. You could just extract it and use the actual executable inside.
