### ISSUE TITLE
Just weird crash upon opening the application.

### ISSUE THREAD

**Issue by Diamondew** [linuslin0/ACST#128]
![ACSaveTool_x64_2023-09-03_00-41-09](https://github.com/linuslin0/ACST/assets/36625681/4433c2a9-9eeb-489e-b15a-2d7cdb25b5cd)

Everytime I open it, Tried running it as administrator, Tried installing all the C++ applications, Nothing worked.

**Comment by linuslin0** [comment]
Please refer to #3
