### ISSUE TITLE
Failed to load save file

### ISSUE THREAD

**Issue by Emilza07** [linuslin0/ACST#130]
Failed to load save game.

I recovered deleted save files and now when I try to put them in the tool or in the savegames folder itself (I'm 99% sure it was the same account) it's not working, could you help me please?
[Files.zip](https://github.com/linuslin0/ACST/files/12642348/Files.zip)

**Comment by linuslin0** [comment]
If you are sure that the account id is correct then likely save data were corrupted, there is nothing this tool can do about that.

**Comment by Emilza07** [comment]
I'm pretty sure + I tried using the detect button. There is no way to recover it, yes?

**Comment by linuslin0** [comment]
Unfortunately no. This tool just simply changes the account id associated with the save, it doesn't modify the actual save data.
