### ISSUE TITLE
Failed to load save file (save3dmgames)

### ISSUE THREAD

**Issue by Spythere** [linuslin0/ACST#131]
Hello! Could anybody help me with converting those files from an old cracked version? I have quite a progress there and I don't want to play from the ground up on my original version (I found it on some old Ubi account I forgot it existed, lol). I have tried to do this reading other gh issues but with no success. Is there any way to do this properly with non-original saves? Thanks in advance!

[save3dmgames.zip](https://github.com/linuslin0/ACST/files/12643992/save3dmgames.zip)

**Comment by linuslin0** [comment]
Please refer to https://github.com/linuslin0/ACST/issues/96#issuecomment-1297658634
I can also help convert those saves but I would need a test save from this game on your account.

**Comment by Spythere** [comment]
I've seen this comment but since it's some messing with file contents I couldn't do this on my own. By a "test save" you mean just a save after starting a new game if I understand correctly?

[test_saves.zip](https://github.com/linuslin0/ACST/files/12665352/test_saves.zip)

**Comment by linuslin0** [comment]
[ac4bf.zip](https://github.com/linuslin0/ACST/files/12695912/ac4bf.zip)
Please try with these converted saves.

**Comment by Spythere** [comment]
They work as they should :) Thank you so much! ❤️
