### ISSUE TITLE
Failed to convert save: Unable to create backup file

### ISSUE THREAD

**Issue by Matsumoto-Denki-Tetsudo** [linuslin0/ACST#134]
Hi! I dunno if my error is different from the 'Failed to load save' in the other thread. 

In my case it says:

-> Processing "ACMirage[ManualSave01].save" ... 
Failed to convert save: Unable to create backup file

I wonder what I am doing wrong, because I am following all the instructions and have used two different savegames so far, but still the error shows up. Please help. Thank you :)

**Comment by Matsumoto-Denki-Tetsudo** [comment]
Update: I think the problem is with Windows 11. I have another PC which runs Windows 10, and ACST successfully converted the file there. Ugh, Windows 11 keeps giving me headaches in everything I do haha :D

**Comment by linuslin0** [comment]
Cool let me know if you see this issue again.
