### ISSUE TITLE
Damaged saved game

### ISSUE THREAD

**Issue by RohanKrishna500** [linuslin0/ACST#135]
Hi,I had a legit copy of ac black flag(uplay version) and my ubisoft subscription got expired,so i downloaded the cracked version from fitgirl(which supports 3dm game save) and i tired to convert my legit save for the cracked version but whenever i start the game i get the "damaged saved game" in the profile.any ways to convert uplay saves to 3dm saves with the .ini file possibly

**Comment by linuslin0** [comment]
This tool only supports saves from legit game copies.

**Comment by RohanKrishna500** [comment]
can u direct me to somewhere else to find the solution to this
