### ISSUE TITLE
Could you share source code? 

### ISSUE THREAD

**Issue by bozkayasalihx** [linuslin0/ACST#136]
* i do wanna take a look at what's inside of source code,  i don't want to share my account id blindly 
* i'll preciate if you share the source code. thanks for the great tools btw

**Comment by linuslin0** [comment]
#67 
There is no need to share your account id, the actual encryption key (just a hash of your account id) could be detected by this tool. The encryption algorithm has already been [documented](https://github.com/linuslin0/ACST/blob/master/FAQ.md#how-does-the-save-encryption-work).

**Comment by bozkayasalihx** [comment]
I didn't know the algorithm was documented. Well I've implement rust version of it and it works well. Thanks again this great package. I'll b ising onwards

**Comment by linuslin0** [comment]
Np, glad it worked out for you. I will close this issue.
