### ISSUE TITLE
the software doesnt open

### ISSUE THREAD

**Issue by max5140** [linuslin0/ACST#137]
hi, i have an issue with the software. i have a error message when i try to open it.
![Screenshot 2023-11-29 212120](https://github.com/linuslin0/ACST/assets/152459122/a7615282-332b-4d06-8bde-ca60266899c7)
please can you help me?

**Comment by linuslin0** [comment]
https://github.com/linuslin0/ACST/blob/master/FAQ.md#7z-sfx-error-during-launch

**Comment by linuslin0** [comment]
Also #3.

**Comment by max5140** [comment]
still not working.

**Comment by max5140** [comment]
Yes, I did everything i read in the other post. Still have the same error
message.

Le sam. 2 déc. 2023, 12 h 13 p.m., Linus L. ***@***.***> a
écrit :

**Comment by linuslin0** [comment]
I don't think you will see the same error as shown on the screenshot, if you extract the exe ITSELF (ACSaveTool_x64.exe), then run the ACSaveTool.exe directly.

**Comment by max5140** [comment]
You mean extracting whats in the .exe file. Or extracting the exe from the
zip? Maybe thats what i missunderstood.

Le mar. 5 déc. 2023, 11 h 15 a.m., Linus L. ***@***.***> a
écrit :

**Comment by linuslin0** [comment]
I mean extracting the exe, it's a packed executable and that error came from the packer. All you need to do is run the actual exe inside.

**Comment by glr8182-del** [comment]
Hi, I'm having an error when starting the software. Can anyone help me?

<img width="770" height="553" alt="Image" src="https://github.com/user-attachments/assets/fbff2ec8-afdc-4829-aadf-83d912f44f17" />

**Comment by glr8182-del** [comment]
Hi, can anyone help me?
