### ISSUE TITLE
Avatar: Frontier of Pandora support

### ISSUE THREAD

**Issue by schmurger** [linuslin0/ACST#139]
Can this program be adapted to support Avatar: Frontier of Pandora save games?
I've attached a save file just in case.
[e6c261fc-0d29-4862-9648-0c9dd20205b1.zip](https://github.com/linuslin0/ACST/files/13642612/e6c261fc-0d29-4862-9648-0c9dd20205b1.zip)

**Comment by linuslin0** [comment]
You should be able to use the save directly without modification. Just rename it to whatever account id you want to use.

**Comment by schmurger** [comment]
I didn't even think the save games are not encrypted! Thank you for a quick reply. The save move does work without any modification.
