### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by TheGreatDemon** [linuslin0/ACST#142]
But how do I find the Game Key for Black Flag?

I've tried every combo I could think of and none were valid.

I have my old save files which were damaged for whatever reason when Ubisoft pushed the newest update. 
What I mean by "damaged" is that when I start the game up, there is no option to continue from an old save. 
It says "Start a new single player game" (or something like that) at the main menu, and upon clicking that, it shows the old file with a new name; "damaged save file" and it has 0% progress instead of 100%.
Clicking on it doesn't work. It just says to delete it.

Could the game version from the old save files be different from the current game version for some reason? If so, how would I go about fixing that?
I REEEEEEEEEEAAAAAAALLLY don't want to have to play through the entire game again and collect everything again. 

Would sending them to you allow you to convert them to work for my PC? 
Or would I still have to do the converting on my end anyway?

----------------------------------------------------------------
Sorry for the essay lol.

**Comment by linuslin0** [comment]
If the actual save data was corrupted then this tool can't help. 
You can find the key in the Account Information, if there is no key shown for that game then please use a test save to let the tool detect the encryption key.
Please share the saves here if you are not sure if they are actually corrupted or was just using a wrong encryption key.

**Comment by TheGreatDemon** [comment]
[AC4BF saves.zip](https://github.com/linuslin0/ACST/files/13747709/AC4BF.saves.zip)

**Comment by linuslin0** [comment]
I was able to load your save without issue after encrypted it using my own game key so I don't think its damaged.
Please start a new game and load it as a test save in the tool, or just post that test save here if you still need help.

**Comment by TheGreatDemon** [comment]
Where is Account Information located? Is it in the Ubisoft Connect launcher?

**Comment by linuslin0** [comment]
> Where is Account Information located? Is it in the Ubisoft Connect launcher?

That's right.

**Comment by TheGreatDemon** [comment]
That was the information I needed to get it to work. If it was written in the instructions somewhere, I obviously skimmed past it, so it is definitely my fault. Thanks for your help!
