### ISSUE TITLE
Are there any dangers of sharing encryption ID?

### ISSUE THREAD

**Issue by PelopasSalore** [linuslin0/ACST#145]
Firstly, I would like to thank you immensely for the tool. It's a silly question, but I have this doubt, would sharing the ID have any risks?

**Comment by linuslin0** [comment]
I wouldn't say it's 100% safe to share it publicly, considering it could be your account id or the game activation key.

**Comment by PelopasSalore** [comment]
> Eu não diria que é 100% seguro compartilhá-lo publicamente, considerando que pode ser o ID da sua conta ou a chave de ativação do jogo.

Thank you for the answer, the tool is excellent and apparently 100% safe.
