### ISSUE TITLE
AC3 Remastered save file not converting to used save file?

### ISSUE THREAD

**Issue by DashYami** [linuslin0/ACST#148]
Not sure if I'm using ACSaveTool right or not, I've used it many ways include using Uplay ID to Encryption ID and or using my save in the Open... part or the used one on it, Not sure if I'm just bad at what to do with ACSaveTool For Assassin's Creed 3 Remastered, Plus it does say "Done!" when I converted the files but still it's not showing the save file in game, if the Converted file is somewhere else or what?
![Screenshot 2024-01-05 162140](https://github.com/linuslin0/ACST/assets/155780618/3dc872a2-d8a2-49b3-8d61-e6667154af8c)

**Comment by linuslin0** [comment]
The save you are trying to convert is the smaller size "Options" save, it's  not your story progress save.
The story saves are usually named as 2.save, 3.save...etc.

**Comment by DashYami** [comment]
So, I can't used a 100% save into my own game if I had to guess?

**Comment by linuslin0** [comment]
You can, it's just you need to pick the right file which is actual story progress save.
Besides the file size, we can also check the "Save info" starts with `AC3RM[x]`, and `x > 0` indicates it's a story save.

**Comment by DashYami** [comment]
All I have seen is to use the ACSaveTool with the save and it'll convert it somehow plus the CODEX.ini doesn't show either way

**Comment by DashYami** [comment]
I've been doing what it's telling me to do (I think) and the new save file doesn't show up
