### ISSUE TITLE
Cant detect the encryption id on AC Unity CODEX version

### ISSUE THREAD

**Issue by Adeel2014255** [linuslin0/ACST#149]
Does it work for cracked versions too?Like i have codex version of ac unity and my account id is  "Player"(not in numbers) in save file.For some reason the tool cant detect the encryption id  nor it allows to type in manually (only some  alphabet  can be typed).

**Comment by linuslin0** [comment]
For the detection to work you will need to first select ACUnity. Also the input validation can be turned off in Preferences dialog (Ctrl + P) -> Validate ID format.
If you still can't get it to work please share the saves. This tool was designed to work with saves from legit game copies.

**Comment by linuslin0** [comment]
Close due to no activities.
