### ISSUE TITLE
Can't convert AC Unity and AC revealation savefile to legit save 

### ISSUE THREAD

**Issue by Angan1317** [linuslin0/ACST#150]
First of all, thanks for this tool
This has been a great help 
I successfully converted AC Syndicate save (cracked version) to my legit save (Steam version)
Didn't need to convert for AC2 and AC Brotherhood, their cracked saves worked as it is for legit versions 
But for AC Unity, its showing failed to convert 
However for AC Revelations, its saying incorrect decryption ID , not able to convert my cracked version saves into legit steam version
I don't know what wrong steps I am doing 
It would be great if you help with this issue

**Comment by Angan1317** [comment]
UPDATE : I could successfully convert my cracked version AC Revelation saves into legit ones 
AC Unity and AC$ Black Flag saves however have still the same issue 
Failed to convert 
Incorrect save file 
Please help me convert saves for those 2 games

**Comment by linuslin0** [comment]
This tool doesn't support non-stand format saves, which are mostly from not-so-legit game copies. #96 
Please share the save you want to convert, as well as test saves generated from the legit game on your account.

**Comment by Angan1317** [comment]
Thanks for understanding and clarifying the issue, sending you the saves in a zip file right away for both Unity and Black Flag

**Comment by Angan1317** [comment]
[AC Unity saves + test save.zip](https://github.com/linuslin0/ACST/files/13896894/AC.Unity.saves.%2B.test.save.zip)
[AC Black Flag saves + test save.zip](https://github.com/linuslin0/ACST/files/13896922/AC.Black.Flag.saves.%2B.test.save.zip)
Here are the files u asked for , for both the games

**Comment by linuslin0** [comment]
Please try with these converted saves. 
[ACBF+ACUnity.zip](https://github.com/linuslin0/ACST/files/13897302/ACBF%2BACUnity.zip)

**Comment by Angan1317** [comment]
UNBELIEVABLE !!!!! Oh My God !!!! Holy Shitttttt 
You actually did it....you actually did it....I can actually use these saves, I can finally play my own saves 
Oh my god u are an absolute gem, a lifesaver.. DUDE u are the best 
Thank you so much 
I am glad I found u and ur thread on the github...OMG 
Both AC4 and AC Unity saves are working on my legit game versions 
I thought I lost those saves for good...but I can actually play my own saves 
Now I am gonna annoy u more hahaha if some other AC game saves have similar issue, so far I have checked every AC game except Rogue, AC3 remastered, Liberation HD and Freedom Cry
speaking of AC3 remastered, I cant use my old AC3 savegames on it right? so no point trying that
about freedom cry and liberation HD, will my old saves work? nvm I actually got back my old freedom cry save in ac4 save it self, thanks to u.. what about liberation? will it work on liberation HD?
and the only one left is rogue..if it doesn't work, I will let u know
Glad to meet another fellow AC fan and lover like me.. or should I say EZIO lover/fan hahah 
Nice to meet u mate

**Comment by linuslin0** [comment]
You're welcome. Glad those saves worked for you.
AC3 saves can't be used in its Remastered release indeed.
As for Liberation HD saves, this tool can convert them to Liberation Remastered, just choose Liberation HD and check Detect for the Decryption ID, then double click the `Encryption ID` text label.
