### ISSUE TITLE
Can't convert AC Black Flag saves: Invalid save file

### ISSUE THREAD

**Issue by tbergeron** [linuslin0/ACST#151]
Hi I'm trying to convert a save game from a FitGirl release of AC Black Flag. I bought the legit game and would like to keep playing the same save.

What I read in the README says I should use the game key as the encryption ID so I tried doing so and ticking the DETECT checkbox for decryption. 

I also tried with an existing save from the legit game for the encryption id.

But what I get is: `Failed to convert save: Invalid save file`

Could you help me please? I don't know what I'm doing wrong 🤷‍♂️

Thanks!

Here is the save in question:
[save3dmgames.zip](https://github.com/linuslin0/ACST/files/14226279/save3dmgames.zip)

Here is a test save:
[testsave.zip](https://github.com/linuslin0/ACST/files/14226284/testsave.zip)

**Comment by linuslin0** [comment]
This tool only supports saves from legit game copies.
Please try with these converted saves. 
[ACBF_converted.zip](https://github.com/linuslin0/ACST/files/14231136/ACBF_converted.zip)

**Comment by tbergeron** [comment]
It worked! Thank you so much!!!
