### ISSUE TITLE
AC Revelations 100% Savegame

### ISSUE THREAD

**Issue by Texmet77** [linuslin0/ACST#153]
Hi everybody!
I played AC Revelations story+side quests with 80% sync and I don't really feel like spending lots of time more on it.
So I downloaded a 100% save to check outfits and other rewards, but I can't get it to work.

I tried to convert the files with your tool, but I had no luck. Once the game starts the files created with your tool are overwritten by the cloud synchronization. What am I doing wrong?

Any help would be appreciated. Tx
Fabio

**Comment by linuslin0** [comment]
The cloud sync can be turned off in Ubisoft Connect client settings. Once you can load the converted save then you can turn it back on.

**Comment by Texmet77** [comment]
OK tx I will give it a try and let you know.

**Comment by Texmet77** [comment]
HI linuslin0. The advice was good, but I seem to do something wrong. The games shows "Damaged Save Game".
Maybe I use your tool not properly, due to not perfect English speaking. So some questions:
- Open: here I should open the 100% save from the other user to convert into my account, right?
- Decryption ID: set to detect
- Encryption ID: my username or click ... and load a save game from mine

Am I doing it right? Tx

**Comment by linuslin0** [comment]
Those steps look good to me. Make sure you selected the right save. For ACR, story save should always be the one with larger size. Usually it's 2.save, but sometimes it can end up in 1.save.

**Comment by Texmet77** [comment]
Tx to your advices I managed it.
Great tool! Have a nice week!
