### ISSUE TITLE
Outputs to same format?

### ISSUE THREAD

**Issue by mfa-usr** [linuslin0/ACST#158]
I am attempting to use this on AC Black Flag/Freedom Cry and am not sure if I am using it correctly. When I open my file using the auto-detect it just saves a new file in its place of the same format. Is this the intended affect? I was hoping to find a tool that decrypts the save file and outputs a plaintext file so that I could edit the values. I read the readme but did not see anywhere what the actual intended effect of the tool is or output formats.

**Comment by linuslin0** [comment]
There is no way to outputs the save as plaintext, the save data are not in plaintext format at the first place.

**Comment by mfa-usr** [comment]
What is it supposed to output to then? Just decoded binary? When I open the file, I just get a bunch of Chinese looking Unicode. How do I edit the save file?

**Comment by linuslin0** [comment]
Yes most stuffs are raw binary and can't be changed directly. There are some plaintext fields you can probably edit like player name. 
Also, this tool is not a save editor, all it can do is just changing the associated account id/game key.
