### ISSUE TITLE
Impossible to proceed because it's not ubisoft game but torrent

### ISSUE THREAD

**Issue by PhytoPlancton** [linuslin0/ACST#161]
Hello, i'm french sorry for my english.

Thanks for your time and for your tool. But in my case, i can't do the process because i don't have the same files than you. Indeed, i downloaded the game with torrent (I already bought the game so i dont want to pay again).

Do you have a process for this games type or not ?

Thanks you.
![Capture](https://github.com/user-attachments/assets/94480e2e-f8be-48b2-a066-9bc0e426d75a)

**Comment by linuslin0** [comment]
Please share the saves you want to convert, as well as a test save from the same game on your account.

**Comment by PhytoPlancton** [comment]
Sorry, I probably misspoke.
I installed a cracked version of AC3, is there any way to skip the first sequence of the game with your software? 

In any case, I didn't succeed because there are folders that I don't have compared to the official version, for example: "Theta".

**Comment by linuslin0** [comment]
If I understand correctly, you would like to use a save that starts with the 2nd sequence of the story. This tool only supports saves from legit game copies. If you want to make it work on this specific version, please share the saves you would like to use/convert, and also a save from whatever version of the game you currently have.

**Comment by PhytoPlancton** [comment]
I decided to buy again the game because I'm loving it, and I was thinking using your tool will be easier but I still can't do it.
I'm totally lost, your tool is good for skipping sequences, I'm right ?

**Comment by linuslin0** [comment]
I think there are still some misunderstandings here.
If "skipping sequences" means you want to use another save file (rather than start a new game save), then yes. But you will need to provide/upload/share your save files here so I can help you convert it. This tool itself does not support saves from non-legit game copies.

**Comment by linuslin0** [comment]
close due to lack of updates.
