### ISSUE TITLE
Please help me - Unable to detect the key

### ISSUE THREAD

**Issue by deodelbarcial** [linuslin0/ACST#162]
Please help me with my Damaged save games of Assassin's Creed Revelations. I'm almost finished with the game at 75%.

I tried using the game but I got an error:
![AC SaveTool](https://github.com/user-attachments/assets/b83de463-5eeb-4789-8e4f-f1d45ccc0c68)

Here's my username: dodiesays.

Here's the damaged saves:
[Damaged saves.zip](https://github.com/user-attachments/files/16202965/Damaged.saves.zip)

Here's the working saves:
[Working saves.zip](https://github.com/user-attachments/files/16202967/Working.saves.zip)

Let me know I missed anything or you need more information.

Thank you very much.

**Comment by linuslin0** [comment]
Your "Damaged saves" are actually not for AC Revelations, looks like those were from AC Black Flag.

**Comment by deodelbarcial** [comment]
Thanks for the response. Looked like my saves got an issue when I restarted my PC while it was saving. I just downloaded this AC Revelations Save Files I found on the web and I think I'll just go off with it, I just want to finished the game and play the DLC next.

Glad that a tool like this exists. Great work!
