### ISSUE TITLE
"Invalid save file"

### ISSUE THREAD

**Issue by alexxD46** [linuslin0/ACST#163]
Trying to convert my current save (i just finished the mission where arno gets his watch back) to a save i got where you just got into the assassin order and have everything unlocked but when i try to convert it, the program says "Invalid save file".
![imagem_2024-07-18_134944228](https://github.com/user-attachments/assets/26187dd2-4053-46d9-9c33-84e5204c6690)

**Comment by linuslin0** [comment]
This tool only supports saves from legit game copies.
If that's the case please share the saves you want to convert, as well as a test save from the game on your account.

**Comment by alexxD46** [comment]
my game is a legit copy, im not sure about the save i downloaded, its not letting me drop the saves here.

**Comment by linuslin0** [comment]
Feel free to drop me an email with those saves.

**Comment by alexxD46** [comment]
I emailed you the saves.
