### ISSUE TITLE
Unable to open

### ISSUE THREAD

**Issue by Rui-CC1225** [linuslin0/ACST#165]
Hello, I would like to understand why I can't open this program
![6d6be9b82ca8e972867f5503a381949](https://github.com/user-attachments/assets/396ddf74-1423-406c-99d3-50e3a1dfac15)

**Comment by onenonlygit** [comment]
Error is slightly different but tool also does not open
![image](https://github.com/user-attachments/assets/c36080ba-4b41-4854-815a-46242a4b8586)

Windows 11, no winrar or winzip or 7zip, using nanazip. 
Uninstalled nanazip, same error. 
Running as admin makes no difference.

**Comment by linuslin0** [comment]
This has already been mentioned on the FAQ page. It's a packer issue rather than the app itself.
https://github.com/linuslin0/ACST/blob/master/FAQ.md#7z-sfx-error-during-launch
