### ISSUE TITLE
Not working on AC Odyssey

### ISSUE THREAD

**Issue by baohon323** [linuslin0/ACST#167]
[storage_files - Copy.zip](https://github.com/user-attachments/files/16799780/storage_files.-.Copy.zip)
Hi, 
can you pls help to fix these save files from AC Odyssey. To be honest, those are non-standard save files so when i use your tool, seem like it does not work.

Thanks

**Comment by linuslin0** [comment]
Those saves can be loaded and converted by the tool without issue. Please make sure you are using the correct Encryption ID for the account you want to use.

**Comment by linuslin0** [comment]
Close due to inactivity.
