### ISSUE TITLE
AC: Unity save corruption every attempt

### ISSUE THREAD

**Issue by pnydiffuser** [linuslin0/ACST#168]
I have tried to replace my old saves with another but no matter how i use the tool it always wants me to make new saves.
My 1.save is in Encryption ID and new save 1 and 2 in save file(s). Importing them into Ubisoft 857 doesn't work.

**Comment by linuslin0** [comment]
I can take a look at your save if you would like. If your 1.save put into the Encryption ID (as test save) is from the account you want to use, then seems like you were doing it correctly.

**Comment by linuslin0** [comment]
Close due to inactivity.
