### ISSUE TITLE
AC4BF

### ISSUE THREAD

**Issue by MyPasswordIs0password** [linuslin0/ACST#171]
Hi i was playing AC4BF pirated version for a while, then i liked the game and i buyed it on ubisoft . I wanted to transfer my savegame and i can't. Please help i can't write encrypted key on the tool. 
[save3dmgames.zip](https://github.com/user-attachments/files/17789405/save3dmgames.zip)
 
The save3dmgames is the pirated version

[73f078d8-6471-4b28-ad2a-12e8632890f2.zip](https://github.com/user-attachments/files/17789406/73f078d8-6471-4b28-ad2a-12e8632890f2.zip)

And this is the buyed game save. Please help thank you !

**Comment by linuslin0** [comment]
Please try with this converted save. The 1.save provided is corrupted so I use 2.save as a test save to detect the encryption key.
[ACBF.zip](https://github.com/user-attachments/files/17823455/ACBF.zip)

**Comment by MyPasswordIs0password** [comment]
Thank you sir, you are a gamers savior!
