### ISSUE TITLE
.sav vs .save

### ISSUE THREAD

**Issue by vtsssss** [linuslin0/ACST#172]
Hi @linuslin0 

my game save files are in .sav format for some reason, the same file i want to convert is in .save format, after i convert and remove the "e" from ".save" the file is detectable in game but the file appears as corrupt

can you help ? 

[My Saves.zip](https://github.com/user-attachments/files/17794628/My.Saves.zip)

**Comment by vtsssss** [comment]
sorry i should mention this is for ac mirage

**Comment by GalaxyXYZ888** [comment]
I have the same problem did you find a fix ?

**Comment by vtsssss** [comment]
Nay no solution yet

**Comment by linuslin0** [comment]
This tool can't produce non-standard format saves. It won't work by just changing the file extension.
