### ISSUE TITLE
Game Update Required! AC Mirage

### ISSUE THREAD

**Issue by Schurkee** [linuslin0/ACST#173]
I played the AC Mirage when it was demo and now after the crack i want to continue it but the first the files were corrupted so i used this tool and now it says "Your saves require a game update. You will not be able to continue until the game update is applied"
can you help me please ? 
[acst_backup.zip](https://github.com/user-attachments/files/17997220/acst_backup.zip)

**Comment by linuslin0** [comment]
Saves from higher versions of this game can't be loaded by a lower version build. There is nothing we can do about that.
