### ISSUE TITLE
ac4 (ac3 actualy too)  - Failed to load save.

### ISSUE THREAD

**Issue by mycop5** [linuslin0/ACST#57]
-> C:\Users\master\Downloads\1589285659_assassins_creed_iv\1.save
-> C:\Users\master\Downloads\1589285659_assassins_creed_iv\2.save
-> Processing "1.save" ... 
Failed to load save.
-> Processing "2.save" ... 
Failed to load save.
Execution time: 0.0088028
trying few different saves

**Comment by mycop5** [comment]
also... how to get Game Key for ac4 if it not show in ubisoft connect? (only ac3 show)

**Comment by linzhouyu** [comment]
This tool doesn't support saves from non-legit game copies, which is most likely the case if those saves were downloaded from Internet. If you still want to convert those saves feel free to send me an email.
And if you can't find the key, just generate a save in the game and use it as a test save. There is a button on the right side of the Encryption ID to let you load it.

**Comment by linuslin0** [comment]
Closing this due to lack of response.
