### ISSUE TITLE
How can I find the decryption ID 

### ISSUE THREAD

**Issue by Thramer** [linuslin0/ACST#58]
This is not necessarily an issue but I am downloading a save game because I need a unreleased outfit for Assassin's Creed Valhalla but the user ID/decryption IS is never mentioned how can I find it?

**Comment by linuslin0** [comment]
Could just use the Detect checkbox on the right side. It will detect the Decryption ID from loaded saves.

**Comment by Thramer** [comment]
But I just want to know the decryption ID I do not want to do anything else

**Comment by linuslin0** [comment]
It's not possible to get the account/user ID in plaintext from saves. It's being hashed before use as encryption key. The detect function is just kind of a brute force attack so we don't need to know the original account ID (as Decryption ID).

**Comment by linuslin0** [comment]
Closing this issue, feel free to reopen if you have more questions on it.
