### ISSUE TITLE
Conversion from CODEX save files doesn't seem to work? 

### ISSUE THREAD

**Issue by Emplexx** [linuslin0/ACST#59]
In advance I'm sorry if piracy is frowned upon here 

I used to play AC Origins back in 2018, it was a CPY crack (a version from before the two DLCs were released), then I updated it to a CODEX crack that did include the DLCs. I have recently purchased the game on Steam and while the older CPY save files converted and worked just fine, when I try to convert the CODEX save files (which are named 0x1.sav, 0x2.sav etc. instead of the common 1.save, 2.save etc) the game simply doesn't see them, all of the save slots are empty. Just wondering if this is intended tool behaviour or a bug etc, and is there any way to convert CODEX save files to legit ones?

Thanks in advance

**Comment by linuslin0** [comment]
CODEX to legit save conversion is supported. Please send me an email with your saves so I can take a look.

**Comment by Emplexx** [comment]
Just sent you the email with saves attached
