### ISSUE TITLE
Invalid Game Title / AC:R / ACST v2.4.3

### ISSUE THREAD

**Issue by slvrwlf** [linuslin0/ACST#60]
Hey! I tried to use on my Assassin's Creed Revelations saves from 2013 and re-played recently. It was not legal game but currently I have legal game. Why do I get  **invalid game title error** from v2.4.3. of this program? Thanks^^

https://prnt.sc/13r2gzy

**Comment by linuslin0** [comment]
Hi there, if you already tried select AC Revelations as the game title with correct username (as decryption id). Please send me your saves, I will take a look. This tool only support legit game saves, there is no guarantee it will work on other types of saves.

**Comment by slvrwlf** [comment]
OKAY! I FOUND THE ISSUE!

My mistake, I tried to use this conversion process from old illegal game save location but, after I moved old saves to the legal Ubisoft save game folder and typed decryption name of the old illegal account and typed encryption my own legal Ubisoft legacy username, it worked! 

Thanks for this program, it is AWESOME! and sorry for I took your time.

**Comment by linuslin0** [comment]
Np, glad it worked. I will close this issue then.
