### ISSUE TITLE
.sav files

### ISSUE THREAD

**Issue by Kostasaek** [linuslin0/ACST#62]
Hi there!
First of all, is this tool only for cpy? 
My rld version seems to be saving my ac4bf save as a .sav instead of .save files.
Can u help me convert .sav to original game file or it wont work at all?
Is there a way that .sav be converted to .save files?
Thanks in advance

**Comment by linuslin0** [comment]
This tool was designed to work with legit save format. Please send me an email with your saves and I will see what I can do.
