### ISSUE TITLE
Unable to detect encryption key AC4BF

### ISSUE THREAD

**Issue by ggereerhhdder** [linuslin0/ACST#63]
When I try to convert a save I found, it simply tells me:
"-> Processing "1.save" ... 
Game title: Assassin's Creed IV Black Flag
Save info: AC4BF[-1]-tm_2021_10_16 03:42:56
... Unable to detect encryption key.

Execution time: 0.0003614"

I was wondering if you could help me, or tell me if I'm doing something wrong. Again, the game is for Assassin's creed Black Flag
Thanks for taking time to respond if you do.

**Comment by linuslin0** [comment]
Please send the save you were trying to convert. I will take a look.

**Comment by ggereerhhdder** [comment]
I'm not sure if this will work or not, so tell me if this works. I think by copying and pasting the link into the top allows the save to download.
[Acr4 save.zip](https://github.com/linuslin0/ACST/files/7358809/Acr4.save.zip)

**Comment by ggereerhhdder** [comment]
I'm pretty sure this is what you're asking for? A save from my profile, right? If so, this is my personal save. Not sure how to make a test save and give it to you, but I'm sure this is what you're asking for. It's my personal save.
[Acr4 Save.zip](https://github.com/linuslin0/ACST/files/7360229/Acr4.Save.zip)

**Comment by ggereerhhdder** [comment]
Yes. I attached my save that I want converted to the 100 percent save. The one I just sent is the one I want converted to the save I sent before.

**Comment by ggereerhhdder** [comment]
It seemed to work, but my progress for the game doesn't seem to be changing. Do I need to replace my old save with the newly converted file, or does it convert automatically after pressing the convert button? It doesn't seem so, as when I try the converting, it says it was done, and worked, but then when I go into the game, nothing seems to have changed. Am I doing something wrong still, or could it be something else? Thanks for taking the time to read and respond to me.
