### ISSUE TITLE
AC Black Flag cannot detect encryption ID

### ISSUE THREAD

**Issue by plato79** [linuslin0/ACST#64]
[437.zip](https://github.com/linuslin0/ACST/files/7379189/437.zip)

I played the game in the past with reloaded version. Now I want to transfer it to original.. I used your tool, although it says "Failed to load save". Is there any way to fix these save files?

**Comment by linuslin0** [comment]
Please also provide the saves.ini along side with those saves you want to convert.

**Comment by linuslin0** [comment]
[AC4BF_.zip](https://github.com/linuslin0/ACST/files/7393529/AC4BF_.zip)
Please try with this converted save (using generic encryption ID). If it not work then you may want to convert it with your own game key.
