### ISSUE TITLE
Support for same Uplay platform Far Cry 6?

### ISSUE THREAD

**Issue by sunjeen** [linuslin0/ACST#65]
Hi is that possible you add support for Far cry 6?

**Comment by saikishi** [comment]
I also hope to support far cry 6

**Comment by InactiveCoyote** [comment]
what about farcry 3 or 4

**Comment by linuslin0** [comment]
@InactiveCoyote  There is save tool exits for FC3 (FC3 Save Helper); And FC4 saves are not encrypted.
There is no plan to support FC saves with this tool. Closing this issue.
