### ISSUE TITLE
Is there a way to edit the save file?

### ISSUE THREAD

**Issue by zhu-ty** [linuslin0/ACST#69]
My save file crashed when I try to load them, the possible reason might be the wrong item counts for some weapons, I wonder if there is a way to edit the weapon counts back to 1?
[5092.zip](https://github.com/linuslin0/ACST/files/7576812/5092.zip)

**Comment by linuslin0** [comment]
No unfortunately. Those data are not stored in human readable plaintext so we won't be to directly modify them.
