### ISSUE TITLE
Failed to load save

### ISSUE THREAD

**Issue by WitheringWyvern** [linuslin0/ACST#70]
trying to convert save but keeps giving this error

-> Processing "1.save" ... 
Failed to load save.

-> Processing "2.save" ... 
Failed to load save.

Execution time: 0.0002785

**Comment by linuslin0** [comment]
Please post the saves you want to convert. Note that this tool doesn't support saves from non-legit game copies.

**Comment by WitheringWyvern** [comment]
it's fine, I restarted
