### ISSUE TITLE
Ac4bf damaged save

### ISSUE THREAD

**Issue by Foxomate** [linuslin0/ACST#71]
When I put a converted save file into my save folder when I launch the game it detects the save file as damaged. Does anyone know anything that could help?
Ps: I have tried numerous different save files, all of which are damaged.

**Comment by linuslin0** [comment]
Most likely you are using a wrong encryption ID. Please upload your saves and I will take a look.

**Comment by Foxomate** [comment]
I am trying to use this save file from nexusmods https://www.nexusmods.com/assassinscreedivblackflag/mods/10?tab=files&file_id=11

**Comment by linuslin0** [comment]
Please also provide a test save from your own account for this game.

**Comment by Foxomate** [comment]
It just says I can't attach a file of that type to a comment.

**Comment by linuslin0** [comment]
You might need to put it into a zip archive, or just send me an email with that.

**Comment by Foxomate** [comment]
[save.zip](https://github.com/linuslin0/ACST/files/7721115/save.zip)

**Comment by linuslin0** [comment]
Looks like your 1.save and 2.save have different encryption ID, not sure if you already replaced your 2.save with something else. I just used your 1.save as test save and converted the save you mentioned earlier.
[ac4bf.zip](https://github.com/linuslin0/ACST/files/7721190/ac4bf.zip)
If this still not work, please remove all existing save files, restart the game and upload the save folder.

**Comment by Foxomate** [comment]
ok, will try. Thanks
