### ISSUE TITLE
Capped Number of Characters I Can Type For IDs

### ISSUE THREAD

**Issue by d1ngd0ng** [linuslin0/ACST#72]
I'm trying to bring over my dodi/theta saves for AC Revelations (2.save) and it seems like the character limit is capped at 15 for the encryption ID. I'm not too sure of the exact number for the decryption ID, but it is similarly capped. Slight tangent, I did input my legacy name for the decryption ID (I changed it once), but it still says invalid decryption key.

Thanks in advance, do let me know if you need any additional information.

**Comment by linuslin0** [comment]
Closing this issue. Feel free to reopen as needed.
