### ISSUE TITLE
AC Valhalla: Corrupted Save Files 

### ISSUE THREAD

**Issue by Logiaa77** [linuslin0/ACST#75]
Hey, first thank you for writing this tool. 

But it doesnt work for me. When I change the ID with the tool, the game tells me the file is corrupted. Even if the uplay_r2.ini is set to the same ID. My game is at Version 1.1.2

**Comment by linuslin0** [comment]
Hi there,
This tool is designed to be used with legit game copies. Besides you won't be able to use a save from higher version of the game, even if you changed its account ID.

**Comment by linuslin0** [comment]
Closing this issue, feel free to add comments if you still have questions.
