### ISSUE TITLE
AC4bf unable to load savefile

### ISSUE THREAD

**Issue by tartaZ2** [linuslin0/ACST#77]
Hello, i try to convert my old free savefile to one legit ubi savefile and i have this error: unable to load savefile can you halp me?
Here my saves
[AC4BF_TEST.zip](https://github.com/linuslin0/ACST/files/7995274/AC4BF_TEST.zip)
[AC4BF.zip](https://github.com/linuslin0/ACST/files/7995277/AC4BF.zip)
Many Thanx!

**Comment by linuslin0** [comment]
Hi,
Please try with these converted saves.
[ACBF_converted.zip](https://github.com/linuslin0/ACST/files/8008316/ACBF_converted.zip)

**Comment by tartaZ2** [comment]
Wow thanx man this works like a sharme! you save my ass and some disk space..
Can i buy you a beer?

**Comment by linuslin0** [comment]
Glad it worked. That's all I need. :) Thanks.
