### ISSUE TITLE
AC Revelation

### ISSUE THREAD

**Issue by tartaZ2** [linuslin0/ACST#78]
Hello, i have corrupt save game when try to convert my old savegame to legit version.
I converted with succes from old skidrow to new theta release and then for legit ubi. But for my legit ubi the savegame is corrupt
Please help me!

[AC2r.zip](https://github.com/linuslin0/ACST/files/8008714/AC2r.zip)
[AC2r_TEST.zip](https://github.com/linuslin0/ACST/files/8008715/AC2r_TEST.zip)

**Comment by tartaZ2** [comment]
Works perfect. Now my animus pack is complete.
Many Thanx!

**Comment by linuslin0** [comment]
Np, closing this issue.
