### ISSUE TITLE
Can i rename profile name?

### ISSUE THREAD

**Issue by ilyatseitlin** [linuslin0/ACST#81]
Hi
can i rename profile name after convert?  Thx <3

**Comment by ilyatseitlin** [comment]
AC 4 Black Flag

**Comment by linuslin0** [comment]
Please follow the steps below to change the save profile name:
1. Decrypt the save you want to modify. Leave Encryption ID field empty.
2. Open the decrypted save using any hex editor.
3. Search for the original profile name (default would be "Abstergo") and replace it with the new name has shorter or same length. Use space for padding if its shorter.
4. Save the modified save and convert again with Encryption ID.

**Comment by linuslin0** [comment]
Closing this issue, please feel free to add comments if you still have questions.
