### ISSUE TITLE
I'm struggling on how to convert the saves.

### ISSUE THREAD

**Issue by chillyrgg** [linuslin0/ACST#84]
Sorry, but I don't know how to do this. I had gotten a 95% save on my own (AC Unity), and it was wiped in one of the updates (I'm just now uncovering this as this is my first time launching it in a while).
I've found a 100% save online I would like to use, however I've heard you must convert it into another type of file to work on the servers. I don't know how to do that, so if someone could help convert it or tell me how to do it, I would greatly appreciate it.
https://mega.nz/file/i8sSRIoC#ENQtVOw8Mij6fLxfVfhvdrVmYD0nk_EicigpFB6DEPk
this is a link to a folder with the saves I would like to play with inside. I didn't know how else to put it here. Sorry!

**Comment by linuslin0** [comment]
Please also share a test save from the game you owned on your account.

**Comment by chillyrgg** [comment]
https://mega.nz/file/y9Mkmbrb#nFGk7ygNwIt5NgRAU1Q1_V76TqBOzuNAt7Kw2KdnESM
these are the files in my game right now if that is what you mean by test save.
Sorry for responding so late!

**Comment by linuslin0** [comment]
[ACUnity.zip](https://github.com/linuslin0/ACST/files/8695631/ACUnity.zip)
Please try with these converted saves. You might need to temporarily disable cloud save sync when you swap the saves.

**Comment by chillyrgg** [comment]
Thank you for helping, sorry, but how can I disable cloud save sync?

**Comment by chillyrgg** [comment]
Hey, thank you so much! It worked and I really appreciate it. Have a great day!

**Comment by MAG1STO** [comment]
@chillyrgg how did you disable saving in the cloud?
