### ISSUE TITLE
Need help converting Syndicate 3DM saves to Official

### ISSUE THREAD

**Issue by JediRhymeTrix** [linuslin0/ACST#85]
I can see that the tool does not support unofficial save files, but I was hoping that you could help me out by converting them manually. 

Saves to be converted:
[ACS_3DM.zip](https://github.com/linuslin0/ACST/files/8796845/ACS_3DM.zip)

Test save for encryption ID:
[ACS_Ubi.zip](https://github.com/linuslin0/ACST/files/8796844/ACS_Ubi.zip)

Thanks in advance!

**Comment by linuslin0** [comment]
Hello, there is no actual game progress save inside the first archive.

**Comment by JediRhymeTrix** [comment]
My bad! Those were the wrong saves. Turns out, the real saves were in the CODEX format (0x1.sav), which worked fine with the tool after renaming to the correct format (1.save). Thanks for your time, though.
