### ISSUE TITLE
Support for more Ubisoft Games?

### ISSUE THREAD

**Issue by v-maxson** [linuslin0/ACST#90]
Is it possible to add support for more Ubisoft games? Or is it possible to get the source code so I can add that support myself?

I'm specifically looking for this to support `Ghost Recon: Wildlands`.

**Comment by linuslin0** [comment]
Other Ubisoft games uses quite different (and stronger) encryption which I don't have idea about it unfortunately. There is no plan for this tool to support those.

**Comment by v-maxson** [comment]
Are there any plans to open-source this tool then?

**Comment by linuslin0** [comment]
I will need to do some refactoring first, which I really don't have an ETA at the moment.
The encryption algorithm used for AC games is actually quite straightforward (XOR block cipher). If you interested just feel free to shot me an email.
