### ISSUE TITLE
Can't find (*.save) file after acst says done

### ISSUE THREAD

**Issue by Lobojulobo** [linuslin0/ACST#93]
Everything works with the save files and this is what ACST says.

-> C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\15d8f68c-8dde-4586-b08e-67db0cc22f27\5059\ACO_Kassandra_Savegame\Saves\1.save
-> C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\15d8f68c-8dde-4586-b08e-67db0cc22f27\5059\ACO_Kassandra_Savegame\Saves\2.save

-> Processing "1.save" ... 
Game title: Assassin's Creed Odyssey
Save info: ACOd[Options]-tm_2020_09_25_03_18_55
... Done.

-> Processing "2.save" ... 
Game title: Assassin's Creed Odyssey
Save info: ACOd[ManualSave01]-tm_2020_09_25_03_16_31
... Done.

Execution time: 0.0353093

but I can't find the (*.save) file.

**Comment by linuslin0** [comment]
Saves were modified in place. Backups could be found in the acst_backup folder.

**Comment by Lobojulobo** [comment]
so they are in the saves folder?

**Comment by Lobojulobo** [comment]
Nvm  it worked thanks for the help
