### ISSUE TITLE
Failed to load save.

### ISSUE THREAD

**Issue by MAG1STO** [linuslin0/ACST#94]
Hi! I downloaded AC Save Tool to convert the save from the game AC IV: Black Flag. There was such an error "Failed to load save.
Execution time: 0.0002722" I tried it in different ways and it doesn't work. It seems the problem is that I'm trying to convert saves from a pirated version of the game. Is there any way to solve this problem?

![image](https://user-images.githubusercontent.com/112285480/187049884-926b458c-482b-40ea-b5f4-4ce7ed0dc991.png)

**Comment by MAG1STO** [comment]
My pirate save
https://mega.nz/file/TFA0ECJQ#6viiuECDk8TEXyYnRAWNmbbHLmcuO3e5WZMvWSLFR3M

**Comment by MAG1STO** [comment]
Оставить комментарий
@linuslin0 I saw that you can convert the save, can you help?

**Comment by MAG1STO** [comment]
**Guys, if you want to convert saves from the pirated version of Assassin's Creed (any version of the game), then use the program "Save Convert Tool By 3DM".** No need to ask for it @linuslin0 After downloading the program, in the "Converted save" field, insert the game key from Uplay (it may not always be necessary to do this), then click on the "From 3DM Save" and "Convert Save" button after you select your save, it is immediately converted!

_Good luck to everyone!_

![image](https://user-images.githubusercontent.com/112285480/187057155-e84e59c0-f681-4251-b231-9b14b80c8c2c.png)

**Comment by RohanKrishna500** [comment]
> Save Convert Tool By 3DM

hi can u send me the download link for that tool

**Comment by Myama93** [comment]
> > Save Convert Tool By 3DM
> 
> hi can u send me the download link for that tool

https://www.playground.ru/assassins_creed_4_black_flag/cheat/assassins_creed_4_black_flag_konverter_sohranenij_save_converter_by_3dm-839241

**Comment by renrenv2** [comment]
Hi @linuslin0  I cant use the 3dm Save file converter by @MAG1STO . Can you convert my save games please. I tried using the AC Save Tool but I got the same result Here are my save files:

https://drive.google.com/drive/folders/1nB7j5Vz8jwwKmn3d1SExzGROhgTeyJ18?usp=drive_link
