### ISSUE TITLE
Green borders?

### ISSUE THREAD

**Issue by GymratGamer** [linuslin0/ACST#95]
Hey!
Had some problems with DLC packs not working to Black flag, so i watched a video on how to fix it. After downloading ACST and following all the steps, I started the game. Now I have green borders on the right side and on the bottom of the screen.  Either mouse or keybord works when i tab in. 

Any help would be much appreciated :)

**Comment by linuslin0** [comment]
From your description I don't think this is related to ACST. Likely the OPTIONS save (the smallest one, usually 1.save) you converted contains certain graphical settings not working well on your machine.

**Comment by GymratGamer** [comment]
Do u know how to fix it?

**Comment by linuslin0** [comment]
Try remove `Assassin's Creed IV Black Flag` folder in `Documents` folder for your Windows account. Next time the game will be launched with default graphical settings.
