### ISSUE TITLE
! Cannot execute "C:\Users\jirok\AppData\Local\Temp\Rar$EXa19788.35448\ACSaveTool_x64.exe"

### ISSUE THREAD

**Issue by ConnorAkshath1** [linuslin0/ACST#99]
Its refusing to execute

**Comment by linuslin0** [comment]
What was the error message?

**Comment by ConnorAkshath1** [comment]
!Cannot Execute! C:\Users\jirok\AppData\Local\Temp\Rar$EXa19788.35448\ACSaveTool_x64.exe

**Comment by ConnorAkshath1** [comment]
Well i managed to open it, whats a decryption key?

**Comment by linuslin0** [comment]
It depends on which game save you want to convert. Please check the readme file on that.

**Comment by xplayerbr** [comment]
mine gives an error after I do the conversion, in mine it says that the save files were corrupted, note I am on the latest version of assassins creed valhalla
